### ISSUE TITLE
GCM send fails on pressing enter

### ISSUE THREAD

**Issue by nikitadagar** [HCI-Quick-Send/Extension#2]
If enter is pressed instead of clicking on send, Webpage not found is shown

Steps to reproduce:
1. Click on QuickSend
2. Enter friend's name and a message.
3. Keep cursor on message input box
4. Press enter

![screenshot 2015-03-31 21 57 53](https://cloud.githubusercontent.com/assets/4637622/6933107/0f8a88b0-d7f1-11e4-8a48-af71288ba848.png)

**Comment by vatsalvora** [comment]
Fixed with updated 1.11. Removed action tag. Also added fix for GCM breaking on update.
